### ISSUE TITLE
Path to output on repo subpath

### ISSUE THREAD

**Issue by sshquack** [cezaraugusto/go-git-it#1]
Hi @cezaraugusto Thanks for creating this neat little tool! I'm running into a small issue. 

1. Cloning a repo root works as expected:

```
❯ go-git-it https://github.com/vercel/next.js output01

Downloading next.js from @vercel/next.js...

Success! next.js downloaded to output01.

❯ ll output01
total 0
drwxr-xr-x  2 user  wheel  64 19 Dec 19:01 next.js/
```

2. Cloning a repo sub path into an output directory ends up in an empty folder:
```
❯ go-git-it https://github.com/vercel/next.js/examples output02

Downloading next.js from @vercel/next.js...

Success! next.js downloaded to output02.

❯ ll output02/next.js
total 0
```

Is there a way to clone a subpath into a output directory?

**Comment by cezaraugusto** [comment]
hi @sshquack! thanks for reporting!

I've just updated the package and you should get your path as expected by running `npx go-git-it https://github.com/vercel/next.js/examples output02`. These are my results:

<img width="1136" alt="Screen Shot 2022-02-04 at 10 54 33" src="https://user-images.githubusercontent.com/4672033/152540711-35c4ebb3-1a94-419f-8a85-f476e4962540.png">

I've removed the colored output so if you still see it, try running `npx clear-npx-cache` to clear npx cache. Current version is 0.2.1.

**Comment by sshquack** [comment]
Hi @cezaraugusto Appreciate the new npm release! I just tried 0.2.1 and it is not working as expected. I want to get only a specific subdirectory (For example: `vercel/next.js/examples`) So when I run this command:
```
go-git-it https://github.com/vercel/next.js/examples output02
```

it should only download the `examples` folder. But right now it is downloading the whole `next.js` directory. I think this is what I see in your screenshot as well. Is there a way to only go-git-it the examples directory?

**Comment by cezaraugusto** [comment]
Did some updates, could you try again? Running `npx go-git-it@latest https://github.com/vercel/next.js/examples output02` works ok here now, but lmk if to you it's not

**Comment by sshquack** [comment]
Awesome -- it works great now. Thanks @cezaraugusto 🥂 

Closing this issue

**Comment by cezaraugusto** [comment]
awesome! glad to help
